#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Nov 06 16:03:38 CET 2018
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto 48ac6283b9034692aa4e8ae3d86af2f0 --incr --debug typical --relax --mt 8 --include "../../../../daq_krm3z30.srcs/sources_1/bd/system/ip/system_GND_1_0/sysc" --include "../../../../daq_krm3z30.srcs/sources_1/bd/system/ip/system_GND_1_0/sim" -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot ddr_reset_tb_behav xil_defaultlib.ddr_reset_tb xil_defaultlib.glbl -log elaborate.log
